### ISSUE TITLE
interpolate() was renamed to interpolateNode() in Reanimated 2. Please use interpolateNode() instead

### ISSUE THREAD

**Issue by fessor10** [gorhom/react-native-animated-tabbar#116]
# I get this error when compiling my code with expo 

``bash
at node_modules/react-native-reanimated/src/reanimated2/interpolation.ts:119:4 in interpolate
at node_modules/react-native-redash/lib/module/Colors.js:1:2605 in interpolateColorsRGB
at node_modules/react-native-redash/lib/module/Colors.js:1:3435 in interpolateColor
at node_modules/@gorhom/animated-tabbar/src/presets/bubble/item/BubbleTabBarItem.tsx:50:28 in BubbleTabBarItemComponent
at [native code]:null in performSyncWorkOnRoot
at [native code]:null in dispatchAction
at node_modules/use-subscription/cjs/use-subscription.development.js:85:14 in checkForUpdates
at node_modules/fbemitter/lib/BaseEventEmitter.js:185:4 in __emitToSubscription
at node_modules/fbemitter/lib/BaseEventEmitter.js:166:10 in emit
at node_modules/react-native-appearance/src/index.tsx:53:6 in Appearance.set
at node_modules/react-native-appearance/src/index.tsx:20:2 in nativeEventEmitter.addListener$argument_1
at node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:189:10 in emit
at [native code]:null in callFunctionReturnFlushedQueue
``

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/animated-tabbar         | 2.1.2   |
| react-native                    |41.0.0   |
| react-native-reanimated         | 2.1.0   |
| react-native-gesture-handler    | 1.10.2  |
| react-native-svg                | 12.1.0   |

## Steps To Reproduce

1. Create a new expo project.
2. Add React Navigation, install dependencies. Using expo install ``react-native-reanimated react-native-gesture-handler react-native-svg``
3. Add ``react-native-animated-tabbar`` and use the library version listed above

**Comment by fessor10** [comment]
@gorhom Hi, can you please kindly have a look at this in your spare time. 

I will be expecting to hear your thoughts on this.

Thank you!

**Comment by JClackett** [comment]
Having the same issue on latest expo build

**Comment by JClackett** [comment]
I think its because this package uses the old react-native-redash package, it needs to be updated

**Comment by JClackett** [comment]
Fixed by using yarn resolution in package json
```
  "resolutions": {
    "react-native-redash": "16.1.1"
  }
```

and downgrading this packages version: 
```
    "@gorhom/animated-tabbar": "2.1.1",
```

**Comment by GuillaumeRZ** [comment]
Same problem here ! Thanks for the update ! :)

**Comment by butri71** [comment]
same here as well!
